title: Bertrand Bosu
description: Notes on building, learning, and figuring things out.
url: "https://bertqrt.github.io"
baseurl: "/bertrandbosu-blog1"
permalink: /writing/:title/
markdown: kramdown
plugins:
  - jekyll-seo-tag
  - jekyll-feed
